# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: authentication.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x61uthentication.proto\x12\x1aworkers_management_service\"\\\n\x15RegisterWorkerRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x14\n\x0cphone_number\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"5\n\x16RegisterWorkerResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"5\n\x12LoginWorkerRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"2\n\x13LoginWorkerResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"&\n\x15\x46orgotPasswordRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\")\n\x16\x46orgotPasswordResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"3\n\x10VerifyOTPRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08otp_code\x18\x02 \x01(\t\"$\n\x11VerifyOTPResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\";\n\x14ResetPasswordRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x14\n\x0cnew_password\x18\x02 \x01(\t\"(\n\x15ResetPasswordResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xd9\x04\n\x15\x41uthManagementService\x12w\n\x0eRegisterWorker\x12\x31.workers_management_service.RegisterWorkerRequest\x1a\x32.workers_management_service.RegisterWorkerResponse\x12n\n\x0bLoginWorker\x12..workers_management_service.LoginWorkerRequest\x1a/.workers_management_service.LoginWorkerResponse\x12w\n\x0e\x46orgotPassword\x12\x31.workers_management_service.ForgotPasswordRequest\x1a\x32.workers_management_service.ForgotPasswordResponse\x12h\n\tVerifyOTP\x12,.workers_management_service.VerifyOTPRequest\x1a-.workers_management_service.VerifyOTPResponse\x12t\n\rResetPassword\x12\x30.workers_management_service.ResetPasswordRequest\x1a\x31.workers_management_service.ResetPasswordResponseB5Z3github.com/example/workers-management-service/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'authentication_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z3github.com/example/workers-management-service/proto'
  _globals['_REGISTERWORKERREQUEST']._serialized_start=52
  _globals['_REGISTERWORKERREQUEST']._serialized_end=144
  _globals['_REGISTERWORKERRESPONSE']._serialized_start=146
  _globals['_REGISTERWORKERRESPONSE']._serialized_end=199
  _globals['_LOGINWORKERREQUEST']._serialized_start=201
  _globals['_LOGINWORKERREQUEST']._serialized_end=254
  _globals['_LOGINWORKERRESPONSE']._serialized_start=256
  _globals['_LOGINWORKERRESPONSE']._serialized_end=306
  _globals['_FORGOTPASSWORDREQUEST']._serialized_start=308
  _globals['_FORGOTPASSWORDREQUEST']._serialized_end=346
  _globals['_FORGOTPASSWORDRESPONSE']._serialized_start=348
  _globals['_FORGOTPASSWORDRESPONSE']._serialized_end=389
  _globals['_VERIFYOTPREQUEST']._serialized_start=391
  _globals['_VERIFYOTPREQUEST']._serialized_end=442
  _globals['_VERIFYOTPRESPONSE']._serialized_start=444
  _globals['_VERIFYOTPRESPONSE']._serialized_end=480
  _globals['_RESETPASSWORDREQUEST']._serialized_start=482
  _globals['_RESETPASSWORDREQUEST']._serialized_end=541
  _globals['_RESETPASSWORDRESPONSE']._serialized_start=543
  _globals['_RESETPASSWORDRESPONSE']._serialized_end=583
  _globals['_AUTHMANAGEMENTSERVICE']._serialized_start=586
  _globals['_AUTHMANAGEMENTSERVICE']._serialized_end=1187
# @@protoc_insertion_point(module_scope)
